import re

ta_hi_matrix = '''  'ta-hi': {
    foundation: {
      id: 'foundation-ta-hi',
      path: 'foundation',
      lang: 'hi',
      uiLang: 'ta',
      title: 'Course 1: Foundation (என் மொழி ஆற்றல் விரிவாக்கம்)',
      description: 'Learn Hindi vowels, nouns, plurals, adjectives, verbs, and vocabulary with Tamil UI prompts.',
      objective: 'Learn Hindi vowels, nouns, plurals, adjectives, verbs, and vocabulary with Tamil UI prompts.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'foundation-ta-hi-l1',
          title: 'Course 1: Foundation (என் மொழி ஆற்றல் விரிவாக்கம்)',
          learning_goal: 'Learn Hindi vowels, nouns, plurals, adjectives, verbs, and vocabulary with Tamil UI prompts.',
          teaching_content: 'Practice reading basic Hindi grammar and vocabulary with Tamil guidance.',
          image_key: 'book',
          practice_questions: [
            {
              id: 'ta_hi_c1_q1',
              question: 'கேள்வி: இந்தி மொழியில் உயிரெழுத்துகள் எத்தனை?',
              options: ['10', '11', '13', '12'],
              correct_index: 2,
              explanation: 'Hindi language has 13 vowels.',
            },
            {
              id: 'ta_hi_c1_q2',
              question: "கேள்வி: 'माँ' (Maa) என்பது எந்த வகைச் சொல்?",
              options: ['क्रिया (கிரியா - வினை)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)', 'सर्वनाम (சர்வநாம் - பிரதிபெயர்)'],
              correct_index: 1,
              explanation: "'Maa' is a Noun (संज्ञा).",
            },
            {
              id: 'ta_hi_c1_q3',
              question: "கேள்வி: 'लड़का' (Ladka) என்பதன் பன்மை?",
              options: ['लड़कियाँ (லட்கியான்)', 'लड़के (லட்கே)', 'लड़कों (லட்கோன்)', 'लड़का (லட்கா)'],
              correct_index: 1,
              explanation: "The plural of 'Ladka' is 'Ladke'.",
            },
            {
              id: 'ta_hi_c1_q4',
              question: "கேள்வி: 'सुंदर' (Sundar) என்பது?",
              options: ['विशेषण (விஷேஷண் - உரிச்சொல்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'सर्वनाम (சர்வநாம் - பிரதிபெயர்)'],
              correct_index: 0,
              explanation: "'Sundar' is an Adjective (विशेषण).",
            },
            {
              id: 'ta_hi_c1_q5',
              question: "கேள்வி: 'पढ़ता' (Padhta) என்பது?",
              options: ['संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'विशेषण (விஷேஷண் - உரிச்சொல்)', 'अव्यय (அவ்யய - இடைச்சொல்)'],
              correct_index: 1,
              explanation: "'Padhta' is a Verb (क्रिया).",
            },
            {
              id: 'ta_hi_c1_q6',
              question: "கேள்வி: 'पुस्तक' (Pustak) என்பதன் சரியான பொருள்?",
              options: ['किताब (கிதாப் - புத்தகம்)', 'सड़क (சடக் - சாலை)', 'पेड़ (பேட் - மரம்)', 'घर (கர் - வீடு)'],
              correct_index: 0,
              explanation: "'Pustak' means Kitab (Book).",
            },
            {
              id: 'ta_hi_c1_q7',
              question: "கேள்வி: 'विद्यालय' (Vidyalaya) என்பதன் பொருள்?",
              options: ['अस्पताल (அஸ்பதால் - மருத்துவமனை)', 'स्कूल (ஸ்கூல் - பள்ளி)', 'बाजार (பாஜார் - சந்தை)', 'खेत (கேத் - வயல்)'],
              correct_index: 1,
              explanation: "'Vidyalaya' means School.",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'ta_hi_c1_cp1', question: 'கேள்வி: இந்தி மொழியில் உயிரெழுத்துகள் எத்தனை?', options: ['10', '11', '13', '12'], correct_index: 2 },
          { id: 'ta_hi_c1_cp2', question: "கேள்வி: 'माँ' (Maa) என்பது எந்த வகைச் சொல்?", options: ['क्रिया (கிரியா - வினை)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)', 'सर्वनाम (சர்வநாம் - பிரதிபெயர்)'], correct_index: 1 },
          { id: 'ta_hi_c1_cp3', question: "கேள்வி: 'लड़का' (Ladka) என்பதன் பன்மை?", options: ['लड़कियाँ (லட்கியான்)', 'लड़के (லட்கே)', 'लड़कों (லட்கோன்)', 'लड़का (லட்கா)'], correct_index: 1 },
          { id: 'ta_hi_c1_cp4', question: "கேள்வி: 'सुंदर' (Sundar) என்பது?", options: ['विशेषण (விஷேஷண் - உரிச்சொல்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'सर्वनाम (சர்வநாம் - பிரதிபெயர்)'], correct_index: 0 },
          { id: 'ta_hi_c1_cp5', question: "கேள்வி: 'पढ़ता' (Padhta) என்பது?", options: ['संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'विशेषण (விஷேஷண் - உரிச்சொல்)', 'अव्यय (அவ்யய - இடைச்சொல்)'], correct_index: 1 },
          { id: 'ta_hi_c1_cp6', question: "கேள்வி: 'पुस्तक' (Pustak) என்பதன் சரியான பொருள்?", options: ['किताब (கிதாப் - புத்தகம்)', 'सड़क (சடக் - சாலை)', 'पेड़ (பேட் - மரம்)', 'घर (கர் - வீடு)'], correct_index: 0 },
          { id: 'ta_hi_c1_cp7', question: "கேள்வி: 'विद्यालय' (Vidyalaya) என்பதன் பொருள்?", options: ['अस्पताल (அஸ்பதால் - மருத்துவமனை)', 'स्कूल (ஸ்கூல் - பள்ளி)', 'बाजार (பாஜார் - சந்தை)', 'खेत (கேத் - வயல்)'], correct_index: 1 },
        ],
      },
      checkpoint_test: [
        { id: 'ta_hi_c1_cp1', question: 'கேள்வி: இந்தி மொழியில் உயிரெழுத்துகள் எத்தனை?', options: ['10', '11', '13', '12'], correct_index: 2, explanation: 'Hindi has 13 vowels.' },
        { id: 'ta_hi_c1_cp2', question: "கேள்வி: 'माँ' (Maa) என்பது எந்த வகைச் சொல்?", options: ['क्रिया (கிரியா - வினை)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)', 'सर्वनाम (சர்வநாம் - பிரதிபெயர்)'], correct_index: 1, explanation: "'Maa' is a Noun." },
        { id: 'ta_hi_c1_cp3', question: "கேள்வி: 'लड़का' (Ladka) என்பதன் பன்மை?", options: ['लड़कियाँ (லட்கியான்)', 'लड़के (லட்கே)', 'लड़कों (லட்கோன்)', 'लड़का (லட்கா)'], correct_index: 1, explanation: "The plural of 'Ladka' is 'Ladke'." },
        { id: 'ta_hi_c1_cp4', question: "கேள்வி: 'सुंदर' (Sundar) என்பது?", options: ['विशेषण (விஷேஷண் - உரிச்சொல்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'सर्वनाम (சர்வநாம் - பிரதிபெயர்)'], correct_index: 0, explanation: "'Sundar' is an Adjective." },
        { id: 'ta_hi_c1_cp5', question: "கேள்வி: 'पढ़ता' (Padhta) என்பது?", options: ['संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'विशेषण (விஷேஷண் - உரிச்சொல்)', 'अव्यय (அவ்யய - இடைச்சொல்)'], correct_index: 1, explanation: "'Padhta' is a Verb." },
        { id: 'ta_hi_c1_cp6', question: "கேள்வி: 'पुस्तक' (Pustak) என்பதன் சரியான பொருள்?", options: ['किताब (கிதாப் - புத்தகம்)', 'सड़क (சடக் - சாலை)', 'पेड़ (பேட் - மரம்)', 'घर (கர் - வீடு)'], correct_index: 0, explanation: "'Pustak' means Book." },
        { id: 'ta_hi_c1_cp7', question: "கேள்வி: 'विद्यालय' (Vidyalaya) என்பதன் பொருள்?", options: ['अस्पताल (அஸ்பதால் - மருத்துவமனை)', 'स्कूल (ஸ்கூல் - பள்ளி)', 'बाजार (பாஜார் - சந்தை)', 'खेत (கேத் - வயல்)'], correct_index: 1, explanation: "'Vidyalaya' means School." },
      ],
    },
    beginner: {
      id: 'beginner-ta-hi',
      path: 'beginner',
      lang: 'hi',
      uiLang: 'ta',
      title: 'Course 2: Beginner (வாக்கியங்களை நேரம்)',
      description: 'Learn Hindi tenses, past/present/future forms, and action words with Tamil UI guidance.',
      objective: 'Learn Hindi tenses, past/present/future forms, and action words with Tamil UI guidance.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'beginner-ta-hi-l1',
          title: 'Course 2: Beginner (வாக்கியங்களை நேரம்)',
          learning_goal: 'Learn Hindi tenses, past/present/future forms, and action words with Tamil UI guidance.',
          teaching_content: 'Practice identifying tenses in Hindi sentences.',
          image_key: 'book',
          practice_questions: [
            {
              id: 'ta_hi_c2_q1',
              question: 'கேள்வி: "मैं स्कूल जाता हूँ।" (Main school jaata hoon) இது எந்த காலம்?',
              options: ['भूतकाल (பூத்காள் - இறந்தகாலம்)', 'वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'आज्ञार्थ (ஆக்யார்த் - கட்டளை)'],
              correct_index: 1,
              explanation: "'Main school jaata hoon' is Present Tense (वर्तमान काल).",
            },
            {
              id: 'ta_hi_c2_q2',
              question: 'கேள்வி: "वह कल आया।" (Vah kal aaya)?',
              options: ['भूतकाल (பூத்காள் - இறந்தகாலம்)', 'वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'कोई नहीं (கோயீ நஹீன் - இல்லை)'],
              correct_index: 0,
              explanation: "'Vah kal aaya' is Past Tense (भूतकाल).",
            },
            {
              id: 'ta_hi_c2_q3',
              question: 'கேள்வி: "मैं कल जाऊँगा।" (Main kal jaaunga)?',
              options: ['वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'भूतकाल (பூத்காள் - இறந்தகாலம்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)'],
              correct_index: 1,
              explanation: "'Main kal jaaunga' is Future Tense (भविष्य काल).",
            },
            {
              id: 'ta_hi_c2_q4',
              question: 'கேள்வி: "सीमा खाना बनाती है।" (Seema khana banati hai)?',
              options: ['वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भूतकाल (பூத்காள் - இறந்தகாலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'],
              correct_index: 0,
              explanation: "'Seema khana banati hai' is Present Tense (वर्तमान काल).",
            },
            {
              id: 'ta_hi_c2_q5',
              question: 'கேள்வி: "खाया" (Khaya) என்பது?',
              options: ['वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'भूत (பூத் - இறந்தகாலம்)', 'कोई नहीं (கோயீ நஹீன் - இல்லை)'],
              correct_index: 2,
              explanation: "'Khaya' is Past Tense (भूत).",
            },
            {
              id: 'ta_hi_c2_q6',
              question: 'கேள்வி: "पढ़ूँगा" (Padhunga)?',
              options: ['भूत (பூத் - இறந்தகாலம்)', 'वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'],
              correct_index: 2,
              explanation: "'Padhunga' is Future Tense (भविष्य).",
            },
            {
              id: 'ta_hi_c2_q7',
              question: 'கேள்வி: "दौड़ रहा है" (Daud raha hai)?',
              options: ['वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भूत (பூத் - இறந்தகாலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)'],
              correct_index: 0,
              explanation: "'Daud raha hai' is Present Tense (वर्तमान).",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'ta_hi_c2_cp1', question: 'கேள்வி: "मैं स्कूल जाता हूँ।" (Main school jaata hoon) இது எந்த காலம்?', options: ['भूतकाल (பூத்காள் - இறந்தகாலம்)', 'वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'आज्ञार्थ (ஆக்யார்த் - கட்டளை)'], correct_index: 1 },
          { id: 'ta_hi_c2_cp2', question: 'கேள்வி: "वह कल आया।" (Vah kal aaya)?', options: ['भूतकाल (பூத்காள் - இறந்தகாலம்)', 'वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'कोई नहीं (கோயீ நஹீன் - இல்லை)'], correct_index: 0 },
          { id: 'ta_hi_c2_cp3', question: 'கேள்வி: "मैं कल जाऊँगा।" (Main kal jaaunga)?', options: ['वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'भूतकाल (பூத்காள் - இறந்தகாலம்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)'], correct_index: 1 },
          { id: 'ta_hi_c2_cp4', question: 'கேள்வி: "सीमा खाना बनाती है।" (Seema khana banati hai)?', options: ['वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भूतकाल (பூத்காள் - இறந்தகாலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'], correct_index: 0 },
          { id: 'ta_hi_c2_cp5', question: 'கேள்வி: "खाया" (Khaya) என்பது?', options: ['वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'भूत (பூத் - இறந்தகாலம்)', 'कोई नहीं (கோயீ நஹீன் - இல்லை)'], correct_index: 2 },
          { id: 'ta_hi_c2_cp6', question: 'கேள்வி: "पढ़ूँगा" (Padhunga)?', options: ['भूत (பூத் - இறந்தகாலம்)', 'वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'], correct_index: 2 },
          { id: 'ta_hi_c2_cp7', question: 'கேள்வி: "दौड़ रहा है" (Daud raha hai)?', options: ['वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भूत (பூத் - இறந்தகாலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)'], correct_index: 0 },
        ],
      },
      checkpoint_test: [
        { id: 'ta_hi_c2_cp1', question: 'கேள்வி: "मैं स्कूल जाता हूँ।" (Main school jaata hoon) இது எந்த காலம்?', options: ['भूतकाल (பூத்காள் - இறந்தகாலம்)', 'वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'आज्ञार्थ (ஆக்யார்த் - கட்டளை)'], correct_index: 1, explanation: 'Present Tense.' },
        { id: 'ta_hi_c2_cp2', question: 'கேள்வி: "वह कल आया।" (Vah kal aaya)?', options: ['भूतकाल (பூத்காள் - இறந்தகாலம்)', 'वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'कोई नहीं (கோயீ நஹீன் - இல்லை)'], correct_index: 0, explanation: 'Past Tense.' },
        { id: 'ta_hi_c2_cp3', question: 'கேள்வி: "मैं कल जाऊँगा।" (Main kal jaaunga)?', options: ['वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'भूतकाल (பூத்காள் - இறந்தகாலம்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)'], correct_index: 1, explanation: 'Future Tense.' },
        { id: 'ta_hi_c2_cp4', question: 'கேள்வி: "सीमा खाना बनाती है।" (Seema khana banati hai)?', options: ['वर्तमान काल (வர்த்மான் காள் - நிகழ்காலம்)', 'भूतकाल (பூத்காள் - இறந்தகாலம்)', 'भविष्य काल (பவிஷ்ய காள் - எதிர்காலம்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'], correct_index: 0, explanation: 'Present Tense.' },
        { id: 'ta_hi_c2_cp5', question: 'கேள்வி: "खाया" (Khaya) என்பது?', options: ['वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'भूत (பூத் - இறந்தகாலம்)', 'कोई नहीं (கோயீ நஹீன் - இல்லை)'], correct_index: 2, explanation: 'Past Tense.' },
        { id: 'ta_hi_c2_cp6', question: 'கேள்வி: "पढ़ूँगा" (Padhunga)?', options: ['भूत (பூத் - இறந்தகாலம்)', 'वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'], correct_index: 2, explanation: 'Future Tense.' },
        { id: 'ta_hi_c2_cp7', question: 'கேள்வி: "दौड़ रहा है" (Daud raha hai)?', options: ['वर्तमान (வர்த்மான் - நிகழ்காலம்)', 'भूत (பூத் - இறந்தகாலம்)', 'भविष्य (பவிஷ்ய - எதிர்காலம்)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)'], correct_index: 0, explanation: 'Present Tense.' },
      ],
    },
    intermediate: {
      id: 'intermediate-ta-hi',
      path: 'intermediate',
      lang: 'hi',
      uiLang: 'ta',
      title: 'Course 3: Intermediate (கருத்துகளை இணைத்தல்)',
      description: 'Learn Hindi conjunctions, connectors, and opposites with Tamil UI guidance.',
      objective: 'Learn Hindi conjunctions, connectors, and opposites with Tamil UI guidance.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'intermediate-ta-hi-l1',
          title: 'Course 3: Intermediate (கருத்துகளை இணைத்தல்)',
          learning_goal: 'Learn Hindi conjunctions, connectors, and opposites with Tamil UI guidance.',
          teaching_content: 'Practice using Hindi connecting words in context.',
          image_key: 'book',
          practice_questions: [
            {
              id: 'ta_hi_c3_q1',
              question: 'கேள்வி: "राम ___ स्कूल गया।" (Ram ___ school gaya)',
              options: ['लेकिन (லேகின் - ஆனால்)', 'और (அவுர் - மற்றும்)', 'वह (வஹ் - அவன்)', 'क्योंकि (க்யோங்கி - ஏனெனில்)'],
              correct_index: 2,
              explanation: "'Ram vah school gaya' uses 'Vah'.",
            },
            {
              id: 'ta_hi_c3_q2',
              question: 'கேள்வி: "माँ और पिता" (Maa aur Pita) இல் இணைப்புச் சொல்?',
              options: ['माँ (மான்)', 'और (அவுர் - மற்றும்)', 'पिता (பிதா)', 'में (மேன்)'],
              correct_index: 1,
              explanation: "'Aur' (और) is the conjunction.",
            },
            {
              id: 'ta_hi_c3_q3',
              question: 'கேள்வி: "वह पढ़ा, लेकिन पास नहीं हुआ।" (Vah padha, lekin paas nahin hua)?',
              options: ['लेकिन (லேகின் - ஆனால்)', 'पढ़ा (படா)', 'पास (பாஸ்)', 'हुआ (ஹுவா)'],
              correct_index: 0,
              explanation: "'Lekin' (लेकिन) is the connector.",
            },
            {
              id: 'ta_hi_c3_q4',
              question: "கேள்வி: \"मैं और तुम\" (Main aur tum) இல் 'और' என்பது?",
              options: ['संयोजक (சன்யோஜக் - இணைப்பு)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'],
              correct_index: 0,
              explanation: "'Aur' is a Conjunction (संयोजक).",
            },
            {
              id: 'ta_hi_c3_q5',
              question: 'கேள்வி: "इसलिए" (Isliye) பயன்பாடு?',
              options: ['कारण और परिणाम (காரண் அவுர் பரிணாம் - காரண விளைவு)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'काल (காள் - காலம்)'],
              correct_index: 0,
              explanation: "'Isliye' is used for cause and effect (कारण और परिणाम).",
            },
            {
              id: 'ta_hi_c3_q6',
              question: 'கேள்வி: சரியான संयोजक (இணைப்பு) எது?',
              options: ['और (அவுர்)', 'किताब (கிதாப்)', 'घर (கர்)', 'दौड़ (தௌட்)'],
              correct_index: 0,
              explanation: "'Aur' (और) is the correct conjunction.",
            },
            {
              id: 'ta_hi_c3_q7',
              question: 'கேள்வி: "या" (Ya) என்பதன் பொருள்?',
              options: ['दो विकल्पों में एक (தோ விகல்போன் மேன் ஏக் - இரண்டு தேர்வுகளில் ஒன்று)', 'समय (சமய் - காலம்)', 'स्थान (ஸ்தான் - இடம்)', 'क्रिया (கிரியா - வினை)'],
              correct_index: 0,
              explanation: "'Ya' means one of two options.",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'ta_hi_c3_cp1', question: 'கேள்வி: "राम ___ स्कूल गया।" (Ram ___ school gaya)', options: ['लेकिन (லேகின் - ஆனால்)', 'और (அவுர் - மற்றும்)', 'वह (வஹ் - அவன்)', 'क्योंकि (க்யோங்கி - ஏனெனில்)'], correct_index: 2 },
          { id: 'ta_hi_c3_cp2', question: 'கேள்வி: "माँ और पिता" (Maa aur Pita) இல் இணைப்புச் சொல்?', options: ['माँ (மான்)', 'और (அவுர் - மற்றும்)', 'पिता (பிதா)', 'में (மேன்)'], correct_index: 1 },
          { id: 'ta_hi_c3_cp3', question: 'கேள்வி: "वह पढ़ा, लेकिन पास नहीं हुआ।" (Vah padha, lekin paas nahin hua)?', options: ['लेकिन (லேகின் - ஆனால்)', 'पढ़ा (படா)', 'पास (பாஸ்)', 'हुआ (ஹுவா)'], correct_index: 0 },
          { id: 'ta_hi_c3_cp4', question: "கேள்வி: \"मैं और तुम\" (Main aur tum) இல் 'और' என்பது?", options: ['संयोजक (சன்யோஜக் - இணைப்பு)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'], correct_index: 0 },
          { id: 'ta_hi_c3_cp5', question: 'கேள்வி: "इसलिए" (Isliye) பயன்பாடு?', options: ['कारण और परिणाम (காரண் அவுர் பரிணாம் - காரண விளைவு)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'काल (காள் - காலம்)'], correct_index: 0 },
          { id: 'ta_hi_c3_cp6', question: 'கேள்வி: சரியான संयोजक (இணைப்பு) எது?', options: ['और (அவுர்)', 'किताब (கிதாப்)', 'घर (கர்)', 'दौड़ (தௌட்)'], correct_index: 0 },
          { id: 'ta_hi_c3_cp7', question: 'கேள்வி: "या" (Ya) என்பதன் பொருள்?', options: ['दो विकल्पों में एक (தோ விகல்போன் மேன் ஏக் - இரண்டு தேர்வுகளில் ஒன்று)', 'समय (சமய் - காலம்)', 'स्थान (ஸ்தான் - இடம்)', 'क्रिया (கிரியா - வினை)'], correct_index: 0 },
        ],
      },
      checkpoint_test: [
        { id: 'ta_hi_c3_cp1', question: 'கேள்வி: "राम ___ स्कूल गया।" (Ram ___ school gaya)', options: ['लेकिन (லேகின் - ஆனால்)', 'और (அவுர் - மற்றும்)', 'वह (வஹ் - அவன்)', 'क्योंकि (க்யோங்கி - ஏனெனில்)'], correct_index: 2, explanation: "'Vah' is correct." },
        { id: 'ta_hi_c3_cp2', question: 'கேள்வி: "माँ और पिता" (Maa aur Pita) இல் இணைப்புச் சொல்?', options: ['माँ (மான்)', 'और (அவுர் - மற்றும்)', 'पिता (பிதா)', 'में (மேன்)'], correct_index: 1, explanation: "'Aur' is correct." },
        { id: 'ta_hi_c3_cp3', question: 'கேள்வி: "वह पढ़ा, लेकिन पास नहीं हुआ।" (Vah padha, lekin paas nahin hua)?', options: ['लेकिन (லேகின் - ஆனால்)', 'पढ़ा (படா)', 'पास (பாஸ்)', 'हुआ (ஹுவா)'], correct_index: 0, explanation: "'Lekin' is correct." },
        { id: 'ta_hi_c3_cp4', question: "கேள்வி: \"मैं और तुम\" (Main aur tum) இல் 'और' என்பது?", options: ['संयोजक (சன்யோஜக் - இணைப்பு)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'विशेषण (விஷேஷண் - உரிச்சொல்)'], correct_index: 0, explanation: "'Aur' is a Conjunction." },
        { id: 'ta_hi_c3_cp5', question: 'கேள்வி: "इसलिए" (Isliye) பயன்பாடு?', options: ['कारण और परिणाम (காரண் அவுர் பரிணாம் - காரண விளைவு)', 'संज्ञा (சங்யா - பெயர்ச்சொல்)', 'क्रिया (கிரியா - வினை)', 'काल (காள் - காலம்)'], correct_index: 0, explanation: "'Isliye' means Cause & Effect." },
        { id: 'ta_hi_c3_cp6', question: 'கேள்வி: சரியான संयोजक (இணைப்பு) எது?', options: ['और (அவுர்)', 'किताब (கிதாப்)', 'घर (கர்)', 'दौड़ (தௌட்)'], correct_index: 0, explanation: "'Aur' is correct." },
        { id: 'ta_hi_c3_cp7', question: 'கேள்வி: "या" (Ya) என்பதன் பொருள்?', options: ['दो विकल्पों में एक (தோ விகல்போன் மேன் ஏக் - இரண்டு தேர்வுகளில் ஒன்று)', 'समय (சமய் - காலம்)', 'स्थान (ஸ்தான் - இடம்)', 'क्रिया (கிரியா - வினை)'], correct_index: 0, explanation: "'Ya' means choice of options." },
      ],
    },
    advanced: {
      id: 'advanced-ta-hi',
      path: 'advanced',
      lang: 'hi',
      uiLang: 'ta',
      title: 'Course 4: Advanced (புரிதலுக்கான வாசிப்பு)',
      description: 'Read Hindi stories and answer comprehension questions with Tamil UI guidance.',
      objective: 'Read Hindi stories and answer comprehension questions with Tamil UI guidance.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'advanced-ta-hi-l1',
          title: 'Course 4: Advanced (புரிதலுக்கான வாசிப்பு)',
          learning_goal: 'Read Hindi stories and answer comprehension questions with Tamil UI guidance.',
          teaching_content: 'Read the story: "राहुल रोज़ स्कूल जाता है। उसे किताबें पढ़ना पसंद है।"',
          image_key: 'book',
          practice_questions: [
            {
              id: 'ta_hi_c4_q1',
              question: 'கேள்வி: राहुल (Rahul) எங்கு செல்கிறான்?',
              options: ['बाज़ार (பாஜார் - சந்தை)', 'स्कूल (ஸ்கூல் - பள்ளி)', 'पार्क (பார்க் - பூங்கா)', 'घर (கர் - வீடு)'],
              correct_index: 1,
              explanation: 'Rahul goes to School (स्कूल).',
            },
            {
              id: 'ta_hi_c4_q2',
              question: 'கேள்வி: राहुल (Rahul)க்கு என்ன பிடிக்கும்?',
              options: ['खेलना (கேல்னா - விளையாடுதல்)', 'किताबें पढ़ना (கிதாபேன் படனா - புத்தகங்கள் படித்தல்)', 'सोना (சோனா - தூங்குதல்)', 'टीवी देखना (டிவி தேக்னா - தொலைக்காட்சி பார்த்தல்)'],
              correct_index: 1,
              explanation: 'Rahul likes reading books (किताबें पढ़ना).',
            },
            {
              id: 'ta_hi_c4_q3',
              question: 'கேள்வி: பகுதி யாரைப் பற்றி?',
              options: ['रीना (ரீனா)', 'राहुल (ராகுல்)', 'मोहन (மோஹன்)', 'सीमा (சீமா)'],
              correct_index: 1,
              explanation: 'Passage is about Rahul.',
            },
            {
              id: 'ta_hi_c4_q4',
              question: "கேள்வி: 'रोज़' (Roz) என்பதன் பொருள்?",
              options: ['हर दिन (ஹர் தின் - ஒவ்வொரு நாள்)', 'कल (கல் - நேற்று)', 'कभी नहीं (கபீ நஹீன் - ஒருபோதும் இல்லை)', 'अगले सप्ताह (அக்லே சப்தாஹ் - அடுத்த வாரம்)'],
              correct_index: 0,
              explanation: "'Roz' means Every day (हर दिन).",
            },
            {
              id: 'ta_hi_c4_q5',
              question: 'கேள்வி: राहुल (Rahul) என்ன செய்கிறான்?',
              options: ['स्कूल जाता है (ஸ்கூல் ஜாதா ஹை - பள்ளிக்குச் செல்கிறான்)', 'खेत जाता है (கேத் ஜாதா ஹை - வயலுக்குச் செல்கிறான்)', 'बाज़ार जाता है (பாஜார் ஜாதா ஹை - சந்தைக்குச் செல்கிறான்)', 'अस्पताल जाता है (அஸ்பதால் ஜாதா ஹை - மருத்துவமனைக்குச் செல்கிறான்)'],
              correct_index: 0,
              explanation: 'Rahul goes to school (स्कूल जाता है).',
            },
            {
              id: 'ta_hi_c4_q6',
              question: 'கேள்வி: பகுதியின் முக்கிய கருத்து?',
              options: ['पढ़ाई और स्कूल की आदत (படாயீ அவுர் ஸ்கூல் கீ ஆதத் - படிப்பு மற்றும் பள்ளி பழக்கம்)', 'यात्रा (யாத்ரா - பயணம்)', 'वर्षा (வர்ஷா - மழை)', 'पर्वत (பர்வத் - மலை)'],
              correct_index: 0,
              explanation: 'Main idea is reading and school habits.',
            },
            {
              id: 'ta_hi_c4_q7',
              question: 'கேள்வி: சரியான கூற்று எது?',
              options: ['राहुल को किताबें पढ़ना पसंद है। (ராகுல் கோ கிதாபேன் படனா பசந்த் ஹை.)', 'राहुल स्कूल नहीं जाता। (ராகுல் ஸ்கூல் நஹீன் ஜாதா.)', 'राहुल केवल खेलता है। (ராகுல் கேவல் கேல்தா ஹை.)', 'राहुल रोज़ सोता रहता है। (ராகுல் ரோஜ் சோதா ரஹ்தா ஹை.)'],
              correct_index: 0,
              explanation: "'Rahul likes reading books' is the correct sentence.",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'ta_hi_c4_cp1', question: 'கேள்வி: राहुल (Rahul) எங்கு செல்கிறான்?', options: ['बाज़ार (பாஜார் - சந்தை)', 'स्कूल (ஸ்கூல் - பள்ளி)', 'पार्क (பார்க் - பூங்கா)', 'घर (கர் - வீடு)'], correct_index: 1 },
          { id: 'ta_hi_c4_cp2', question: 'கேள்வி: राहुल (Rahul)க்கு என்ன பிடிக்கும்?', options: ['खेलना (கேல்னா - விளையாடுதல்)', 'किताबें पढ़ना (கிதாபேன் படனா - புத்தகங்கள் படித்தல்)', 'सोना (சோனா - தூங்குதல்)', 'टीवी देखना (டிவி தேக்னா - தொலைக்காட்சி பார்த்தல்)'], correct_index: 1 },
          { id: 'ta_hi_c4_cp3', question: 'கேள்வி: பகுதி யாரைப் பற்றி?', options: ['रीना (ரீனா)', 'राहुल (ராகுல்)', 'मोहन (மோஹன்)', 'सीमा (சீமா)'], correct_index: 1 },
          { id: 'ta_hi_c4_cp4', question: "கேள்வி: 'रोज़' (Roz) என்பதன் பொருள்?", options: ['हर दिन (ஹர் தின் - ஒவ்வொரு நாள்)', 'कल (கல் - நேற்று)', 'कभी नहीं (கபீ நஹீன் - ஒருபோதும் இல்லை)', 'अगले सप्ताह (அக்லே சப்தாஹ் - அடுத்த வாரம்)'], correct_index: 0 },
          { id: 'ta_hi_c4_cp5', question: 'கேள்வி: राहुल (Rahul) என்ன செய்கிறான்?', options: ['स्कूल जाता है (ஸ்கூல் ஜாதா ஹை - பள்ளிக்குச் செல்கிறான்)', 'खेत जाता है (கேத் ஜாதா ஹை - வயலுக்குச் செல்கிறான்)', 'बाज़ार जाता है (பாஜார் ஜாதா ஹை - சந்தைக்குச் செல்கிறான்)', 'अस्पताल जाता है (அஸ்பதால் ஜாதா ஹை - மருத்துவமனைக்குச் செல்கிறான்)'], correct_index: 0 },
          { id: 'ta_hi_c4_cp6', question: 'கேள்வி: பகுதியின் முக்கிய கருத்து?', options: ['पढ़ाई और स्कूल की आदत (படாயீ அவுர் ஸ்கூல் கீ ஆதத் - படிப்பு மற்றும் பள்ளி பழக்கம்)', 'यात्रा (யாத்ரா - பயணம்)', 'वर्षा (வர்ஷா - மழை)', 'पर्वत (பர்வத் - மலை)'], correct_index: 0 },
          { id: 'ta_hi_c4_cp7', question: 'கேள்வி: சரியான கூற்று எது?', options: ['राहुल को किताबें पढ़ना पसंद है। (ராகுல் கோ கிதாபேன் படனா பசந்த் ஹை.)', 'राहुल स्कूल नहीं जाता। (ராகுல் ஸ்கூல் நஹீன் ஜாதா.)', 'राहुल केवल खेलता है। (ராகுல் கேவல் கேல்தா ஹை.)', 'राहुल रोज़ सोता रहता है। (ராகுல் ரோஜ் சோதா ரஹ்தா ஹை.)'], correct_index: 0 },
        ],
      },
      checkpoint_test: [
        { id: 'ta_hi_c4_cp1', question: 'கேள்வி: राहुल (Rahul) எங்கு செல்கிறான்?', options: ['बाज़ार (பாஜார் - சந்தை)', 'स्कूल (ஸ்கூல் - பள்ளி)', 'पार्क (பார்க் - பூங்கா)', 'घर (கர் - வீடு)'], correct_index: 1, explanation: 'Rahul goes to school.' },
        { id: 'ta_hi_c4_cp2', question: 'கேள்வி: राहुल (Rahul)க்கு என்ன பிடிக்கும்?', options: ['खेलना (கேல்னா - விளையாடுதல்)', 'किताबें पढ़ना (கிதாபேன் படனா - புத்தகங்கள் படித்தல்)', 'सोना (சோனா - தூங்குதல்)', 'टीवी देखना (டிவி தேக்னா - தொலைக்காட்சி பார்த்தல்)'], correct_index: 1, explanation: 'Rahul likes reading books.' },
        { id: 'ta_hi_c4_cp3', question: 'கேள்வி: பகுதி யாரைப் பற்றி?', options: ['रीना (ரீனா)', 'राहुल (ராகுல்)', 'मोहन (மோஹன்)', 'सीमा (சீமா)'], correct_index: 1, explanation: 'Passage is about Rahul.' },
        { id: 'ta_hi_c4_cp4', question: "கேள்வி: 'रोज़' (Roz) என்பதன் பொருள்?", options: ['हर दिन (ஹர் தின் - ஒவ்வொரு நாள்)', 'कल (கல் - நேற்று)', 'कभी नहीं (கபீ நஹீன் - ஒருபோதும் இல்லை)', 'अगले सप्ताह (அக்லே சப்தாஹ் - அடுத்த வாரம்)'], correct_index: 0, explanation: "'Roz' means Every day." },
        { id: 'ta_hi_c4_cp5', question: 'கேள்வி: राहुल (Rahul) என்ன செய்கிறான்?', options: ['स्कूल जाता है (ஸ்கூல் ஜாதா ஹை - பள்ளிக்குச் செல்கிறான்)', 'खेत जाता है (கேத் ஜாதா ஹை - வயலுக்குச் செல்கிறான்)', 'बाज़ार जाता है (பாஜார் ஜாதா ஹை - சந்தைக்குச் செல்கிறான்)', 'अस्पताल जाता है (அஸ்பதால் ஜாதா ஹை - மருத்துவமனைக்குச் செல்கிறான்)'], correct_index: 0, explanation: 'Rahul goes to school.' },
        { id: 'ta_hi_c4_cp6', question: 'கேள்வி: பகுதியின் முக்கிய கருத்து?', options: ['पढ़ाई और स्कूल की आदत (படாயீ அவுர் ஸ்கூல் கீ ஆதத் - படிப்பு மற்றும் பள்ளி பழக்கம்)', 'यात्रा (யாத்ரா - பயணம்)', 'वर्षा (வர்ஷா - மழை)', 'पर्वत (பர்வத் - மலை)'], correct_index: 0, explanation: 'Main idea is reading and school habit.' },
        { id: 'ta_hi_c4_cp7', question: 'கேள்வி: சரியான கூற்று எது?', options: ['राहुल को किताबें पढ़ना पसंद है। (ராகுல் கோ கிதாபேன் படனா பசந்த் ஹை.)', 'राहुल स्कूल नहीं जाता। (ராகுல் ஸ்கூல் நஹீன் ஜாதா.)', 'राहुल केवल खेलता है। (ராகுல் கேவல் கேல்தா ஹை.)', 'राहुल रोज़ सोता रहता है। (ராகுல் ரோஜ் சோதா ரஹ்தா ஹை.)'], correct_index: 0, explanation: "'Rahul likes reading books' is correct." },
      ],
    },
  },
'''

hi_ta_matrix = '''  'hi-ta': {
    foundation: {
      id: 'foundation-hi-ta',
      path: 'foundation',
      lang: 'ta',
      uiLang: 'hi',
      title: 'Course 1: Foundation (मेरा पठन आत्मविश्वास)',
      description: 'Learn Tamil vowels, nouns, plurals, adjectives, verbs, and vocabulary with Hindi UI prompts.',
      objective: 'Learn Tamil vowels, nouns, plurals, adjectives, verbs, and vocabulary with Hindi UI prompts.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'foundation-hi-ta-l1',
          title: 'Course 1: Foundation (मेरा पठन आत्मविश्वास)',
          learning_goal: 'Learn Tamil vowels, nouns, plurals, adjectives, verbs, and vocabulary with Hindi UI prompts.',
          teaching_content: 'Practice reading basic Tamil grammar and vocabulary with Hindi guidance.',
          image_key: 'book',
          practice_questions: [
            {
              id: 'hi_ta_c1_q1',
              question: 'प्रश्न: तमिल भाषा में स्वर कितने हैं?',
              options: ['10', '11', '12', '13'],
              correct_index: 2,
              explanation: 'Tamil language has 12 vowels.',
            },
            {
              id: 'hi_ta_c1_q2',
              question: "प्रश्न: 'அம்மா' (Amma) किस प्रकार का शब्द है?",
              options: ['வினைச்சொல் (வினைச்சொல் - क्रिया)', 'பெயர்ச்சொல் (பெயர்ச்சொல் - संज्ञा)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)', 'இடைச்சொல் (இடைச்சொல் - अव्यय)'],
              correct_index: 1,
              explanation: "'Amma' is a Noun (பெயர்ச்சொல்).",
            },
            {
              id: 'hi_ta_c1_q3',
              question: "प्रश्न: 'மரம்' (Maram) का बहुवचन क्या है?",
              options: ['மரம் (மரம்)', 'மரங்கள் (மரங்கள்)', 'மரங்கள்ல் (மரங்கள்ல்)', 'மரத்தால் (மரத்தால்)'],
              correct_index: 1,
              explanation: "The plural of 'Maram' is 'Marangal' (மரங்கள்).",
            },
            {
              id: 'hi_ta_c1_q4',
              question: 'प्रश्न: तमिल अक्षर कुल कितने हैं?',
              options: ['247', '146', '216', '100'],
              correct_index: 0,
              explanation: 'Total Tamil letters are 247.',
            },
            {
              id: 'hi_ta_c1_q5',
              question: "प्रश्न: 'படிக்கிறேன்' (Padikkiren) क्या है?",
              options: ['பெயர் (பெயர் - संज्ञा)', 'வினைச்சொல் (வினைச்சொல் - क्रिया)', 'இடைச்சொல் (இடைச்சொல் - अव्यय)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)'],
              correct_index: 1,
              explanation: "'Padikkiren' is a Verb (வினைச்சொல்).",
            },
            {
              id: 'hi_ta_c1_q6',
              question: "प्रश्न: 'நல்ல' (Nalla) क्या है?",
              options: ['உரிச்சொல் (உரிச்சொல் - विशेषण)', 'பெயர் (பெயர் - संज्ञा)', 'வினை (வினை - क्रिया)', 'இடைச்சொல் (இடைச்சொல் - अव्यय)'],
              correct_index: 0,
              explanation: "'Nalla' is an Adjective (உரிச்சொல்).",
            },
            {
              id: 'hi_ta_c1_q7',
              question: "प्रश्न: 'புத்தகம்' (Puthagam) का सही अर्थ क्या है?",
              options: ['மரம் (மரம் - पेड़)', 'நூல் (நூல் - किताब)', 'வீடு (வீடு - घर)', 'கடல் (கடல் - समुद्र)'],
              correct_index: 1,
              explanation: "'Puthagam' means Book (நூல் / किताब).",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'hi_ta_c1_cp1', question: 'प्रश्न: तमिल भाषा में स्वर कितने हैं?', options: ['10', '11', '12', '13'], correct_index: 2 },
          { id: 'hi_ta_c1_cp2', question: "प्रश्न: 'அம்மா' (Amma) किस प्रकार का शब्द है?", options: ['வினைச்சொல் (வினைச்சொல் - क्रिया)', 'பெயர்ச்சொல் (பெயர்ச்சொல் - संज्ञा)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)', 'இடைச்சொல் (இடைச்சொல் - अव्यय)'], correct_index: 1 },
          { id: 'hi_ta_c1_cp3', question: "प्रश्न: 'மரம்' (Maram) का बहुवचन क्या है?", options: ['மரம் (மரம்)', 'மரங்கள் (மரங்கள்)', 'மரங்கள்ல் (மரங்கள்ல்)', 'மரத்தால் (மரத்தால்)'], correct_index: 1 },
          { id: 'hi_ta_c1_cp4', question: 'प्रश्न: तमिल अक्षर कुल कितने हैं?', options: ['247', '146', '216', '100'], correct_index: 0 },
          { id: 'hi_ta_c1_cp5', question: "प्रश्न: 'படிக்கிறேன்' (Padikkiren) क्या है?", options: ['பெயர் (பெயர் - संज्ञा)', 'வினைச்சொல் (வினைச்சொல் - क्रिया)', 'இடைச்சொல் (இடைச்சொல் - அவ்யய)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)'], correct_index: 1 },
          { id: 'hi_ta_c1_cp6', question: "प्रश्न: 'நல்ல' (Nalla) क्या है?", options: ['உரிச்சொல் (உரிச்சொல் - विशेषण)', 'பெயர் (பெயர் - संज्ञा)', 'வினை (வினை - क्रिया)', 'இடைச்சொல் (இடைச்சொல் - அவ்யய)'], correct_index: 0 },
          { id: 'hi_ta_c1_cp7', question: "प्रश्न: 'புத்தகம்' (Puthagam) का सही अर्थ क्या है?", options: ['மரம் (மரம் - पेड़)', 'நூல் (நூல் - किताब)', 'வீடு (வீடு - घर)', 'கடல் (கடல் - समुद्र)'], correct_index: 1 },
        ],
      },
      checkpoint_test: [
        { id: 'hi_ta_c1_cp1', question: 'प्रश्न: तमिल भाषा में स्वर कितने हैं?', options: ['10', '11', '12', '13'], correct_index: 2, explanation: 'Tamil has 12 vowels.' },
        { id: 'hi_ta_c1_cp2', question: "प्रश्न: 'அம்மா' (Amma) किस प्रकार का शब्द है?", options: ['வினைச்சொல் (வினைச்சொல் - क्रिया)', 'பெயர்ச்சொல் (பெயர்ச்சொல் - संज्ञा)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)', 'இடைச்சொல் (இடைச்சொல் - அவ்யய)'], correct_index: 1, explanation: "'Amma' is a Noun." },
        { id: 'hi_ta_c1_cp3', question: "प्रश्न: 'மரம்' (Maram) का बहुवचन क्या है?", options: ['மரம் (மரம்)', 'மரங்கள் (மரங்கள்)', 'மரங்கள்ல் (மரங்கள்ல்)', 'மரத்தால் (மரத்தால்)'], correct_index: 1, explanation: "The plural of 'Maram' is 'Marangal'." },
        { id: 'hi_ta_c1_cp4', question: 'प्रश्न: तमिल अक्षर कुल कितने हैं?', options: ['247', '146', '216', '100'], correct_index: 0, explanation: 'Total Tamil letters are 247.' },
        { id: 'hi_ta_c1_cp5', question: "प्रश्न: 'படிக்கிறேன்' (Padikkiren) क्या है?", options: ['பெயர் (பெயர் - संज्ञा)', 'வினைச்சொல் (வினைச்சொல் - क्रिया)', 'இடைச்சொல் (இடைச்சொல் - அவ்யய)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)'], correct_index: 1, explanation: "'Padikkiren' is a Verb." },
        { id: 'hi_ta_c1_cp6', question: "प्रश्न: 'நல்ல' (Nalla) क्या है?", options: ['உரிச்சொல் (உரிச்சொல் - विशेषण)', 'பெயர் (பெயர் - संज्ञा)', 'வினை (வினை - क्रिया)', 'இடைச்சொல் (இடைச்சொல் - அவ்யய)'], correct_index: 0, explanation: "'Nalla' is an Adjective." },
        { id: 'hi_ta_c1_cp7', question: "प्रश्न: 'புத்தகம்' (Puthagam) का सही अर्थ क्या है?", options: ['மரம் (மரம் - पेड़)', 'நூல் (நூல் - किताब)', 'வீடு (வீடு - घर)', 'கடல் (கடல் - समुद्र)'], correct_index: 1, explanation: "'Puthagam' means Book." },
      ],
    },
    beginner: {
      id: 'beginner-hi-ta',
      path: 'beginner',
      lang: 'ta',
      uiLang: 'hi',
      title: 'Course 2: Beginner (रोज़मर्रा की क्रियाएँ)',
      description: 'Learn Tamil tenses, past/present/future forms, and action words with Hindi UI guidance.',
      objective: 'Learn Tamil tenses, past/present/future forms, and action words with Hindi UI guidance.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'beginner-hi-ta-l1',
          title: 'Course 2: Beginner (रोज़मर्रा की क्रियाएँ)',
          learning_goal: 'Learn Tamil tenses, past/present/future forms, and action words with Hindi UI guidance.',
          teaching_content: 'Practice identifying tenses in Tamil sentences with Hindi guidance.',
          image_key: 'book',
          practice_questions: [
            {
              id: 'hi_ta_c2_q1',
              question: 'प्रश्न: "நான் பள்ளிக்கு செல்கிறேன்।" (Naan pallikku selkiren) यह कौन-सा काल है?',
              options: ['இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இல்லை (இல்லை - कोई नहीं)'],
              correct_index: 1,
              explanation: "'Naan pallikku selkiren' is Present Tense (நிகழ்காலம் / वर्तमान काल).",
            },
            {
              id: 'hi_ta_c2_q2',
              question: 'प्रश्न: "அவன் நேற்று வந்தான்।" (Avan netru vandhan)?',
              options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'கட்டளை (கட்டளை - आज्ञार्थ)'],
              correct_index: 2,
              explanation: "'Avan netru vandhan' is Past Tense (இறந்தகாலம் / भूतकाल).",
            },
            {
              id: 'hi_ta_c2_q3',
              question: 'प्रश्न: "நான் நாளை செல்வேன்।" (Naan naalai selven)?',
              options: ['நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'இல்லை (இல்லை - कोई नहीं)'],
              correct_index: 1,
              explanation: "'Naan naalai selven' is Future Tense (எதிர்காலம் / भविष्य काल).",
            },
            {
              id: 'hi_ta_c2_q4',
              question: 'प्रश्न: "அவள் பாடுகிறாள்।" (Avaal paadugiraal)?',
              options: ['நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'பெயர்ச்சொல் (பெயர்ச்சொல் - संज्ञा)'],
              correct_index: 0,
              explanation: "'Avaal paadugiraal' is Present Tense (நிகழ்காலம்).",
            },
            {
              id: 'hi_ta_c2_q5',
              question: 'प्रश्न: "வந்தான்" (Vandhan) क्या है?',
              options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இடைச்சொல் (இடைச்சொல் - अव्यय)'],
              correct_index: 1,
              explanation: "'Vandhan' is Past Tense (இறந்தகாலம்).",
            },
            {
              id: 'hi_ta_c2_q6',
              question: 'प्रश्न: "படிப்பேன்" (Padipppen)?',
              options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'பெயர் (பெயர் - संज्ञा)'],
              correct_index: 0,
              explanation: "'Padipppen' is Future Tense (எதிர்காலம்).",
            },
            {
              id: 'hi_ta_c2_q7',
              question: 'प्रश्न: "சாப்பிட்டான்" (Saapittaan)?',
              options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)'],
              correct_index: 1,
              explanation: "'Saapittaan' is Past Tense (இறந்தகாலம்).",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'hi_ta_c2_cp1', question: 'प्रश्न: "நான் பள்ளிக்கு செல்கிறேன்।" (Naan pallikku selkiren) यह कौन-सा काल है?', options: ['இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இல்லை (இல்லை - कोई नहीं)'], correct_index: 1 },
          { id: 'hi_ta_c2_cp2', question: 'प्रश्न: "அவன் நேற்று வந்தான்।" (Avan netru vandhan)?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'கட்டளை (கட்டளை - आज्ञार्थ)'], correct_index: 2 },
          { id: 'hi_ta_c2_cp3', question: 'प्रश्न: "நான் நாளை செல்வேன்।" (Naan naalai selven)?', options: ['நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'இல்லை (இல்லை - कोई नहीं)'], correct_index: 1 },
          { id: 'hi_ta_c2_cp4', question: 'प्रश्न: "அவள் பாடுகிறாள்।" (Avaal paadugiraal)?', options: ['நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'பெயர்ச்சொல் (பெயர்ச்சொல் - संज्ञा)'], correct_index: 0 },
          { id: 'hi_ta_c2_cp5', question: 'प्रश्न: "வந்தான்" (Vandhan) क्या है?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இடைச்சொல் (இடைச்சொல் - அவ்யய)'], correct_index: 1 },
          { id: 'hi_ta_c2_cp6', question: 'प्रश्न: "படிப்பேன்" (Padipppen)?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'பெயர் (பெயர் - संज्ञा)'], correct_index: 0 },
          { id: 'hi_ta_c2_cp7', question: 'प्रश्न: "சாப்பிட்டான்" (Saapittaan)?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)'], correct_index: 1 },
        ],
      },
      checkpoint_test: [
        { id: 'hi_ta_c2_cp1', question: 'प्रश्न: "நான் பள்ளிக்கு செல்கிறேன்।" (Naan pallikku selkiren) यह कौन-सा काल है?', options: ['இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இல்லை (இல்லை - कोई नहीं)'], correct_index: 1, explanation: 'Present Tense.' },
        { id: 'hi_ta_c2_cp2', question: 'प्रश्न: "அவன் நேற்று வந்தான்।" (Avan netru vandhan)?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'கட்டளை (கட்டளை - आज्ञार्थ)'], correct_index: 2, explanation: 'Past Tense.' },
        { id: 'hi_ta_c2_cp3', question: 'प्रश्न: "நான் நாளை செல்வேன்।" (Naan naalai selven)?', options: ['நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'இல்லை (இல்லை - कोई नहीं)'], correct_index: 1, explanation: 'Future Tense.' },
        { id: 'hi_ta_c2_cp4', question: 'प्रश्न: "அவள் பாடுகிறாள்।" (Avaal paadugiraal)?', options: ['நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'பெயர்ச்சொல் (பெயர்ச்சொல் - संज्ञा)'], correct_index: 0, explanation: 'Present Tense.' },
        { id: 'hi_ta_c2_cp5', question: 'प्रश्न: "வந்தான்" (Vandhan) क्या है?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இடைச்சொல் (இடைச்சொல் - அவ்யய)'], correct_index: 1, explanation: 'Past Tense.' },
        { id: 'hi_ta_c2_cp6', question: 'प्रश्न: "படிப்பேன்" (Padipppen)?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'பெயர் (பெயர் - संज्ञा)'], correct_index: 0, explanation: 'Future Tense.' },
        { id: 'hi_ta_c2_cp7', question: 'प्रश्न: "சாப்பிட்டான்" (Saapittaan)?', options: ['எதிர்காலம் (எதிர்காலம் - भविष्य काल)', 'இறந்தகாலம் (இறந்தகாலம் - भूतकाल)', 'நிகழ்காலம் (நிகழ்காலம் - वर्तमान काल)', 'உரிச்சொல் (உரிச்சொல் - विशेषण)'], correct_index: 1, explanation: 'Past Tense.' },
      ],
    },
    intermediate: {
      id: 'intermediate-hi-ta',
      path: 'intermediate',
      lang: 'ta',
      uiLang: 'hi',
      title: 'Course 3: Intermediate (मेरे दिन का वर्णन)',
      description: 'Learn Tamil conjunctions, connectors, and opposites with Hindi UI guidance.',
      objective: 'Learn Tamil conjunctions, connectors, and opposites with Hindi UI guidance.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'intermediate-hi-ta-l1',
          title: 'Course 3: Intermediate (मेरे दिन का वर्णन)',
          learning_goal: 'Learn Tamil conjunctions, connectors, and opposites with Hindi UI guidance.',
          teaching_content: 'Practice using Tamil connecting words in context with Hindi guidance.',
          image_key: 'book',
          practice_questions: [
            {
              id: 'hi_ta_c3_q1',
              question: 'प्रश्न: "ரவி ___ பள்ளிக்கு சென்றான்।" (Ravi ___ pallikku sendraan)',
              options: ['ஆனால் (ஆனால் - लेकिन)', 'மற்றும் (மற்றும் - और)', 'இன்று (இன்று - आज)', 'அவன் (அவன் - वह)'],
              correct_index: 3,
              explanation: "'Ravi avan pallikku sendraan' uses 'அவன்' (vav).",
            },
            {
              id: 'hi_ta_c3_q2',
              question: 'प्रश्न: "அம்மா மற்றும் அப்பா" (Amma matrum appa) में इணैप्புச்சோல்?',
              options: ['அம்மா (அம்மா)', 'மற்றும் (மற்றும் - और)', 'அப்பா (அப்பா)', 'இல் (இல்)'],
              correct_index: 1,
              explanation: "'மற்றும்' (Matrum - Aur) is the conjunction.",
            },
            {
              id: 'hi_ta_c3_q3',
              question: 'प्रश्न: "அவன் படித்தான், ஆனால் தேர்ச்சி பெறவில்லை।" (Avan padithaan, aanaal thercci peravillai)?',
              options: ['ஆனால் (ஆனால் - لیکن)', 'அவன் (அவன்)', 'படித்தான் (படித்தான்)', 'தேர்ச்சி (தேர்ச்சி)'],
              correct_index: 0,
              explanation: "'ஆனால்' (Aanaal - Lekin) is the connector.",
            },
            {
              id: 'hi_ta_c3_q4',
              question: 'प्रश्न: "நானும் நீயும்" (Naanum neeyum)?',
              options: ['இணைப்பு (இணைப்பு - संयोजक)', 'வினை (வினை - क्रिया)', 'பெயர் (பெயர் - संज्ञा)', 'காலம் (காலம் - काल)'],
              correct_index: 0,
              explanation: "'Naanum neeyum' uses Conjunction (இணைப்பு / संयोजक).",
            },
            {
              id: 'hi_ta_c3_q5',
              question: 'प्रश्न: "எனவே" (Enave) प्रयोग?',
              options: ['காரண விளைவு (காரண விளைவு - कारण और परिणाम)', 'பெயர் (பெயர் - संज्ञा)', 'வினை (வினை - क्रिया)', 'காலம் (காலம் - काल)'],
              correct_index: 0,
              explanation: "'Enave' is used for cause & effect (காரண விளைவு).",
            },
            {
              id: 'hi_ta_c3_q6',
              question: 'प्रश्न: सही இணைப்பு (संयोजक) कौन-सा है?',
              options: ['மற்றும் (மற்றும்)', 'வீடு (வீடு)', 'புத்தகம் (புத்தகம்)', 'ஓடு (ஓடு)'],
              correct_index: 0,
              explanation: "'மற்றும்' (Matrum) is the correct conjunction.",
            },
            {
              id: 'hi_ta_c3_q7',
              question: 'प्रश्न: "அல்லது" (Alladhu) का अर्थ क्या है?',
              options: ['இரண்டு தேர்வுகளில் ஒன்று (இரண்டு தேர்வுகளில் ஒன்று - दो विकल्पों में एक)', 'காலம் (காலம் - समय)', 'பெயர் (பெயர் - नाम)', 'வினை (வினை - क्रिया)'],
              correct_index: 0,
              explanation: "'Alladhu' means one of two options.",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'hi_ta_c3_cp1', question: 'प्रश्न: "ரவி ___ பள்ளிக்கு சென்றான்।" (Ravi ___ pallikku sendraan)', options: ['ஆனால் (ஆனால் - लेकिन)', 'மற்றும் (மற்றும் - और)', 'இன்று (இன்று - আজ)', 'அவன் (அவன் - वह)'], correct_index: 3 },
          { id: 'hi_ta_c3_cp2', question: 'प्रश्न: "அம்மா மற்றும் அப்பா" (Amma matrum appa) में इணैप्புச்சோல்?', options: ['அம்மா (அம்மா)', 'மற்றும் (மற்றும் - और)', 'அப்பா (அப்பா)', 'இல் (இல்)'], correct_index: 1 },
          { id: 'hi_ta_c3_cp3', question: 'प्रश्न: "அவன் படித்தான், ஆனால் தேர்ச்சி பெறவில்லை।" (Avan padithaan, aanaal thercci peravillai)?', options: ['ஆனால் (ஆனால் - लेकिन)', 'அவன் (அவன்)', 'படித்தான் (படித்தான்)', 'தேர்ச்சி (தேர்ச்சி)'], correct_index: 0 },
          { id: 'hi_ta_c3_cp4', question: 'प्रश्न: "நானும் நீயும்" (Naanum neeyum)?', options: ['இணைப்பு (இணைப்பு - संयोजक)', 'வினை (வினை - क्रिया)', 'பெயர் (பெயர் - संज्ञा)', 'காலம் (காலம் - काल)'], correct_index: 0 },
          { id: 'hi_ta_c3_cp5', question: 'प्रश्न: "எனவே" (Enave) प्रयोग?', options: ['காரண விளைவு (காரண விளைவு - कारण और परिणाम)', 'பெயர் (பெயர் - संज्ञा)', 'வினை (வினை - क्रिया)', 'காலம் (காலம் - काल)'], correct_index: 0 },
          { id: 'hi_ta_c3_cp6', question: 'प्रश्न: सही இணைப்பு (संयोजक) कौन-सा है?', options: ['மற்றும் (மற்றும்)', 'வீடு (வீடு)', 'புத்தகம் (புத்தகம்)', 'ஓடு (ஓடு)'], correct_index: 0 },
          { id: 'hi_ta_c3_cp7', question: 'प्रश्न: "அல்லது" (Alladhu) का अर्थ क्या है?', options: ['இரண்டு தேர்வுகளில் ஒன்று (இரண்டு தேர்வுகளில் ஒன்று - दो विकल्पों में एक)', 'காலம் (காலம் - समय)', 'பெயர் (பெயர் - नाम)', 'வினை (வினை - क्रिया)'], correct_index: 0 },
        ],
      },
      checkpoint_test: [
        { id: 'hi_ta_c3_cp1', question: 'प्रश्न: "ரவி ___ பள்ளிக்கு சென்றான்।" (Ravi ___ pallikku sendraan)', options: ['ஆனால் (ஆனால் - लेकिन)', 'மற்றும் (மற்றும் - और)', 'இன்று (இன்று - आज)', 'அவன் (அவன் - वह)'], correct_index: 3, explanation: "'Avan' is correct." },
        { id: 'hi_ta_c3_cp2', question: 'प्रश्न: "அம்மா மற்றும் அப்பா" (Amma matrum appa) में इணैप्புச்சோல்?', options: ['அம்மா (அம்மா)', 'மற்றும் (மற்றும் - और)', 'அப்பா (அப்பா)', 'இல் (இல்)'], correct_index: 1, explanation: "'Matrum' is correct." },
        { id: 'hi_ta_c3_cp3', question: 'प्रश्न: "அவன் படித்தான், ஆனால் தேர்ச்சி பெறவில்லை।" (Avan padithaan, aanaal thercci peravillai)?', options: ['ஆனால் (ஆனால் - लेकिन)', 'அவன் (அவன்)', 'படித்தான் (படித்தான்)', 'தேர்ச்சி (தேர்ச்சி)'], correct_index: 0, explanation: "'Aanaal' is correct." },
        { id: 'hi_ta_c3_cp4', question: 'प्रश्न: "நானும் நீயும்" (Naanum neeyum)?', options: ['இணைப்பு (இணைப்பு - संयोजक)', 'வினை (வினை - क्रिया)', 'பெயர் (பெயர் - संज्ञा)', 'காலம் (காலம் - काल)'], correct_index: 0, explanation: 'Conjunction.' },
        { id: 'hi_ta_c3_cp5', question: 'प्रश्न: "எனவே" (Enave) प्रयोग?', options: ['காரண விளைவு (காரண விளைவு - कारण और परिणाम)', 'பெயர் (பெயர் - संज्ञा)', 'வினை (வினை - क्रिया)', 'காலம் (காலம் - काल)'], correct_index: 0, explanation: 'Cause and effect.' },
        { id: 'hi_ta_c3_cp6', question: 'प्रश्न: सही இணைப்பு (संयोजक) कौन-सा है?', options: ['மற்றும் (மற்றும்)', 'வீடு (வீடு)', 'புத்தகம் (புத்தகம்)', 'ஓடு (ஓடு)'], correct_index: 0, explanation: "'Matrum' is correct." },
        { id: 'hi_ta_c3_cp7', question: 'प्रश्न: "அல்லது" (Alladhu) का अर्थ क्या है?', options: ['இரண்டு தேர்வுகளில் ஒன்று (இரண்டு தேர்வுகளில் ஒன்று - दो विकल्पों में एक)', 'காலம் (காலம் - समय)', 'பெயர் (பெயர் - नाम)', 'வினை (வினை - क्रिया)'], correct_index: 0, explanation: 'Choice of options.' },
      ],
    },
    advanced: {
      id: 'advanced-hi-ta',
      path: 'advanced',
      lang: 'ta',
      uiLang: 'hi',
      title: 'Course 4: Advanced (मैं पढ़ सकता/सकती हूँ कहानियाँ)',
      description: 'Read Tamil stories and answer comprehension questions with Hindi UI guidance.',
      objective: 'Read Tamil stories and answer comprehension questions with Hindi UI guidance.',
      certificate_criteria: { min_score_percent: 70 },
      lessons: [
        {
          id: 'advanced-hi-ta-l1',
          title: 'Course 4: Advanced (मैं पढ़ सकता/सकती हूँ कहानियाँ)',
          learning_goal: 'Read Tamil stories and answer comprehension questions with Hindi UI guidance.',
          teaching_content: 'Read the story: "ராம் தினமும் பள்ளிக்குச் செல்கிறான். அவன் புத்தகங்களை விரும்புகிறான்।"',
          image_key: 'book',
          practice_questions: [
            {
              id: 'hi_ta_c4_q1',
              question: 'प्रश्न: ராம் (Ram) कहाँ जाता है?',
              options: ['சந்தை (சந்தை - बाज़ार)', 'பள்ளி (பள்ளி - स्कूल)', 'பூங்கா (பூங்கா - पार्क)', 'வீடு (வீடு - घर)'],
              correct_index: 1,
              explanation: 'Ram goes to School (பள்ளி / स्कूल).',
            },
            {
              id: 'hi_ta_c4_q2',
              question: 'प्रश्न: ராமுக்கு (Ram) क्या पसंद है?',
              options: ['விளையாட்டு (விளையாட்டு - खेलना)', 'புத்தகங்கள் (புத்தகங்கள் - किताबें पढ़ना)', 'திரைப்படம் (திரைப்படம் - फिल्म)', 'இசை (இசை - संगीत)'],
              correct_index: 1,
              explanation: 'Ram likes reading books (புத்தகங்கள்).',
            },
            {
              id: 'hi_ta_c4_q3',
              question: 'प्रश्न: यह गद्यांश किसके बारे में है?',
              options: ['சீதா (சீதா)', 'ராம் (ராம்)', 'குமார் (குமார்)', 'லலிதா (லலிதா)'],
              correct_index: 1,
              explanation: 'Passage is about Ram (ராம்).',
            },
            {
              id: 'hi_ta_c4_q4',
              question: "प्रश्न: 'தினமும்' (Thinamum) का अर्थ क्या है?",
              options: ['சில நேரம் (சில நேரம் - कभी-कभी)', 'ஒவ்வொரு நாள் (ஒவ்வொரு நாள் - हर दिन)', 'நேற்று (நேற்று - कल)', 'நாளை (நாளை - आने वाला कल)'],
              correct_index: 1,
              explanation: "'Thinamum' means Every day (ஒவ்வொரு நாள் / हर दिन).",
            },
            {
              id: 'hi_ta_c4_q5',
              question: 'प्रश्न: ராம் (राम) क्या करता है?',
              options: ['பள்ளிக்குச் செல்கிறான் (स्कूल जाता है)', 'தூங்குகிறான் (சோதா ஹை)', 'ஓடுகிறான் (தௌட்தா ஹை)', 'பாடுகிறான் (காத்தா ஹை)'],
              correct_index: 0,
              explanation: 'Ram goes to school (பள்ளிக்குச் செல்கிறான்).',
            },
            {
              id: 'hi_ta_c4_q6',
              question: 'प्रश्न: गद्यांश का मुख्य विचार क्या है?',
              options: ['பள்ளி செல்லும் பழக்கம் (पढ़ाई और स्कूल की आदत)', 'கடல் (समुद्र)', 'மழை (बारिश)', 'மலை (पहाड़)'],
              correct_index: 0,
              explanation: 'Main idea is school habit.',
            },
            {
              id: 'hi_ta_c4_q7',
              question: 'प्रश्न: सही कथन चुनिए।',
              options: ['ராம் புத்தகங்களை விரும்புகிறான். (राम पुस्तकों को पसंद करता है।)', 'ராம் பள்ளிக்குச் செல்லவில்லை. (राम स्कूल नहीं जाता।)', 'ராம் தினமும் தூங்குகிறான். (राम रोज़ सोता है।)', 'ராம் கிரிக்கெட் மட்டும் விளையாடுகிறான். (राम केवल क्रिकेट खेलता है。)'],
              correct_index: 0,
              explanation: "'Ram likes reading books' is correct.",
            },
          ],
        },
      ],
      checkpoint: {
        min_pass_score: 70,
        questions: [
          { id: 'hi_ta_c4_cp1', question: 'प्रश्न: ராம் (Ram) कहाँ जाता है?', options: ['சந்தை (சந்தை - बाज़ार)', 'பள்ளி (பள்ளி - स्कूल)', 'பூங்கா (பூங்கா - पार्क)', 'வீடு (வீடு - घर)'], correct_index: 1 },
          { id: 'hi_ta_c4_cp2', question: 'प्रश्न: ராமுக்கு (Ram) क्या पसंद है?', options: ['விளையாட்டு (விளையாட்டு - खेलना)', 'புத்தகங்கள் (புத்தகங்கள் - किताबें पढ़ना)', 'திரைப்படம் (திரைப்படம் - फिल्म)', 'இசை (இசை - संगीत)'], correct_index: 1 },
          { id: 'hi_ta_c4_cp3', question: 'प्रश्न: यह गद्यांश किसके बारे में है?', options: ['சீதா (சீதா)', 'ராம் (ராம்)', 'குமார் (குமார்)', 'லலிதா (லலிதா)'], correct_index: 1 },
          { id: 'hi_ta_c4_cp4', question: "प्रश्न: 'தினமும்' (Thinamum) का अर्थ क्या है?", options: ['சில நேரம் (சில நேரம் - कभी-कभी)', 'ஒவ்வொரு நாள் (ஒவ்வொரு நாள் - हर दिन)', 'நேற்று (நேற்று - कल)', 'நாளை (நாளை - आने वाला कल)'], correct_index: 1 },
          { id: 'hi_ta_c4_cp5', question: 'प्रश्न: ராம் (राम) क्या करता है?', options: ['பள்ளிக்குச் செல்கிறான் (स्कूल जाता है)', 'தூங்குகிறான் (सोता है)', 'ஓடுகிறான் (दौड़ता है)', 'பாடுகிறான் (गाता है)'], correct_index: 0 },
          { id: 'hi_ta_c4_cp6', question: 'प्रश्न: गद्यांश का मुख्य विचार क्या है?', options: ['பள்ளி செல்லும் பழக்கம் (पढ़ाई और स्कूल की आदत)', 'கடல் (समुद्र)', 'மழை (बारिश)', 'மலை (पहाड़)'], correct_index: 0 },
          { id: 'hi_ta_c4_cp7', question: 'प्रश्न: सही कथन चुनिए।', options: ['ராம் புத்தகங்களை விரும்புகிறான். (राम पुस्तकों को पसंद करता है।)', 'ராம் பள்ளிக்குச் செல்லவில்லை. (राम स्कूल नहीं जाता।)', 'ராம் தினமும் தூங்குகிறான். (राम रोज़ सोता है।)', 'ராம் கிரிக்கெட் மட்டும் விளையாடுகிறான். (राम केवल क्रिकेट खेलता है。)'], correct_index: 0 },
        ],
      },
      checkpoint_test: [
        { id: 'hi_ta_c4_cp1', question: 'प्रश्न: ராம் (Ram) कहाँ जाता है?', options: ['சந்தை (சந்தை - बाज़ार)', 'பள்ளி (பள்ளி - स्कूल)', 'பூங்கா (பூங்கா - पार्क)', 'வீடு (வீடு - घर)'], correct_index: 1, explanation: 'School.' },
        { id: 'hi_ta_c4_cp2', question: 'प्रश्न: ராமுக்கு (Ram) क्या पसंद है?', options: ['விளையாட்டு (விளையாட்டு - खेलना)', 'புத்தகங்கள் (புத்தகங்கள் - किताबें पढ़ना)', 'திரைப்படம் (திரைப்படம் - फिल्म)', 'இசை (இசை - संगीत)'], correct_index: 1, explanation: 'Books.' },
        { id: 'hi_ta_c4_cp3', question: 'प्रश्न: यह गद्यांश किसके बारे में है?', options: ['சீதா (சீதா)', 'ராம் (ராம்)', 'குமார் (குமார்)', 'லலிதா (லலிதா)'], correct_index: 1, explanation: 'Ram.' },
        { id: 'hi_ta_c4_cp4', question: "प्रश्न: 'தினமும்' (Thinamum) का अर्थ क्या है?", options: ['சில நேரம் (சில நேரம் - कभी-कभी)', 'ஒவ்வொரு நாள் (ஒவ்வொரு நாள் - हर दिन)', 'நேற்று (நேற்று - कल)', 'நாளை (நாளை - आने वाला कल)'], correct_index: 1, explanation: 'Every day.' },
        { id: 'hi_ta_c4_cp5', question: 'प्रश्न: ராம் (राम) क्या करता है?', options: ['பள்ளிக்குச் செல்கிறான் (स्कूल जाता है)', 'தூங்குகிறான் (सोता है)', 'ஓடுகிறான் (दौड़ता है)', 'பாடுகிறான் (गाता है)'], correct_index: 0, explanation: 'Goes to school.' },
        { id: 'hi_ta_c4_cp6', question: 'प्रश्न: गद्यांश का मुख्य विचार क्या है?', options: ['பள்ளி செல்லும் பழக்கம் (पढ़ाई और स्कूल की आदत)', 'கடல் (समुद्र)', 'மழை (बारिश)', 'மலை (पहाड़)'], correct_index: 0, explanation: 'School habit.' },
        { id: 'hi_ta_c4_cp7', question: 'प्रश्न: सही कथन चुनिए।', options: ['ராம் புத்தகங்களை விரும்புகிறான். (राम पुस्तकों को पसंद करता है।)', 'ராம் பள்ளிக்குச் செல்லவில்லை. (राम स्कूल नहीं जाता।)', 'ராம் தினமும் தூங்குகிறான். (राम रोज़ सोता है।)', 'ராம் கிரிக்கெட் மட்டும் விளையாடுகிறான். (राम केवल क्रिकेट खेलता है。)'], correct_index: 0, explanation: 'Ram likes books.' },
      ],
    },
  },
'''

filepath = '/home/surya/Downloads/LiteralAI/backend/src/data/bilingualCourses.js'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

insert_index = content.rfind('};')
if insert_index != -1:
    new_content = content[:insert_index] + ta_hi_matrix + hi_ta_matrix + content[insert_index:]
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print("Successfully appended ta-hi and hi-ta course matrices!")
else:
    print("Error: Could not find closing };")
